name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: List the contents of the current directory. 
        run: |
          ls -alrt
          echo "Hello World" > hello_world.txt
          ls -alrt
        
      - name: Run a One Line script
        run: echo Jaya, Guru Datta !!

      - name: Run a Multi Line Script. 
        run: |
          echo "Twamasmin Karya Niryoge, Pranamam Hari Sattama "
          echo "Hauman Yatna Ma Staya, Dukha Kshaya Kaor Bhavet"
          echo "Tawamsamin Kraya Niryoge, Pranamam Hari Sattama. "
          echo "Raghava Stat Samarambham, Mayi Yatno Paro Bhavet. "

  
